branches:
  only:
  - master
sudo: required
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  include:
  - language: objective-c
    os: osx
    osx_image: xcode9.2
    env: LANE=ios
    before_install:
    - nvm install 8
    - brew install gnupg
  - language: android
    env: LANE=android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-25.0.2
      - build-tools-25.0.3
      - android-23
      - android-25
      - android-26
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      licenses:
      - android-sdk-license-.+
      - google-gdk-license-.+
    before_install:
    - nvm install 8
  - language: javascript
    env: LANE=js
    node_js:
    - '8'
install:
- ".travis/install.sh"
script:
- ".travis/build.sh"
env:
  global:
  - secure: I/VLo06SgsAKbVK7HeKQnVN3mQuL3nlZ+Rqqz/Q8iWEyyyKbQrVC0pXxLfMHsYVPMCkOYZ7A+eSBHFnpKhOM3JpvxK7FmT0ilFu6HPkoELMFIW3Qduk5lcb5qTy+9cmL7Z/HN3Aw/+ujh+Y9wiC1dBUSxN2K573h2Bc3XukLhC140SqBQFQLhDIdZ1yUiR0Fneso3eN6t2IYd6HRhh9VSxrISBgkUjrKeGILUISVb8bFUcpUSg9nr8+Oo6Nl46nz+BwBiP8wAbREBk4BaZ96Q76Xyn01ub8QuJujQBYWtc/qcv4h/HH1hqZ+OOdpoCkHQVwfq+mwDhetdKclj56lEBRWfYbyK+2SZGbq8egnHIXbziUQ547u7l09q9CthnyDZ1nalbUy10dnWo9vs0emaDSoM7EkTQfTZVYt8O+ltAd9QV3Q6WcW/o3BWq01FozA47TfS3XmCOKkLgHQQ3Vf9DgZdiGVBHNnnYE2MKjujUohKRHjiqw7pYUuPOa1D2UXnTnqw1IAeZ6Bt8ba/GwjbG0qskJwEHdeIZNcIeLsVNLJy8sPWbml/DvNOLpGO6xZQx5+PMOpC9VAKBixkNbeSlxH1uyxjbg5VaebMK91Q65sCjDLYHHHF5FRDRphpiqlD4sOzpzoO4+dJjugpfBsljFHAP4m0yHTGoa4DIfnAbU=
  - secure: uTokzD9T+87Fur8fy/0Z0dWV5azghEHKGkF0i30aFrf5sYf80U0CJf2WygyT523TM2A3M5FRAfTAN1eRY2uXHmB5HDeVIFBqNyOATTO/EP7jabtVS95q7Leq56Law5LcNosgYnKlQ2BkjhtvKA9NipvWvDjhClHFapfqMlLKgDQ4MuOM3GjK3gqaRIZdxWU62Nxw2qLZGt2sFaRi3osIxUyxjEV7OaFw1Mu0K03XYiI15TaP06HdavPN9xAmr3XIswOhSPt0yxCYi9HrMI6cKEycLVqoxnYyxx0O05ZuswTWr2W4dX8q5z7zSzbAIpOMSQ2jjgQnBym9ax3goG+qKwskmlzTifzjpPRTIEvn+VNcMWZBbeUpR7ohV4iWNf8mm8dipVq5O0mMXE/G1Aq5VNRQaGcO9JOCysPBSx2qlugfmSYp1XKqEQoAj+ieJodwbDFzQJHBeeixkAGIXf1ThPzT2I9MIYa1MhSrKRWYw2mdUJQUmB9wf12lUcvOZxzpfRuuRfEOQaBH8wWNvHgOLOpDbFlIY6eYahvTYvHJLMjr0Uib5HNTG/D3Ou+aYlJIRZ8uUnUBObR00MDRucbp9CBkXio9TuTjr/Rc+LC408RXd+2HLSXGIWO2kIgbC7xtK0cRbNtErP2eqlN924awVLt+KddVWus1cijWz2CWOw8=
  - secure: nxSG3AzO+uGG+WVCCUicEeLChMMDXG7p19quC6dCRvy7TxgO8oLye2Q5xLS33RqOED5McHSGGNdB1ca+ANu7AsYnzXVNJDCnzYYLodvf2zQyHAdxGlpP/s37mrXFklcxDscACjq45PJrdAcewnW8WZF4ZqlfFpBxpcb+VpUSl2F8XunnECy1bg3KS1nqUt14T1IVE9+OAAkyHRzPArR6IWfSvItluqMR5M4E7JcKe7Csze6yW6iant725Pj/4lc6VDwGE+R+0JvS6TxDR7aty0ktFduS5ENgDqILn4Kf8plBeq+ZMaHGjbd8nPIP1eslTljRIyTfa3t3bEEhVpZYB90j6VfVdhX/evS3CfkS++nNnZ+kqvUXNvQYJ9lYlv3XyCang0jZBNbVh8Y6+o/eBa8jWqT4OYweRbtIX6hqWAf9CIQ/PJxSY69Pbw+R/skbZPpc44T3v1fxqvXqHiz4ktvAR0guKt3u3WvFCCoyGikUaXhb0qzJ29RT/FErpLscTbKRHT8AsX/chiJxjOkJEkorCcrgkYIVOFHzjeD1lIBH3xS6DV9wVnbnt1KbSiS5pSyD+pHMdKG5ovwTWtgLY6e7VbHtCvnEfsdCinLeE/ogfI0Yez9Kig7KHZoHxsXd6IB33FCesX10rQqImrXCdhNmsHJEPaoNpT/kwzOT5/8=
  - secure: jzXHSXsNEqzDCR1C6cHFZFgip/YxgfcUfwVklHtXSztAWLb33ZmgKGmBpx4B5Ieds318NAi3pAz7j0FcAWU4WtIUKoEX5QDc25Ay1Y/l/L+FjRbPcuUeQChoXiCA8nVgW3ZH6RbFe0olQA8BLMHFwalUrp2rPRFUwI1yWphceiXgXbPtnYua+shstTjG3Y/tBQMOiPHsVCUtSgozNNI7v2A2+4kaufxG6WxARCsXlwAn5DEcSeecvKe+1WlqdH5yRbOr1dc5r0uaIr1qc4gN6H8ZrcuFwh/oQ4qjwbShzvnuUCBrFXdRwyJhfzlh+8PeIrjqhKg4Mzmf/gNPPUzhs7SN4oQ+6LYKPrPVBtnAWcQOWc6QEakEpXg5JaDELVfDC4ilTl8wPZvf8BlI83AH8rwVIRvC1fkKDRjD4+/zGdGWATD52NNYoJ799nSyDGqGua5CuOUNQPwmjKE6uMc05l2jx+p4Z6aAV6YApEPcNNdVstjJOykMIZy00u+/Jr1XWs4AjVS7BYlcymNGKwG2uHV0dX3x9sPJdr/ugCzARWrvDOxv/c780aZFUqB5tiDpme072yfiVzCT3kPvvHmw9z5iqS3GdjoHp9GrXeOwJklxh4sVDWzcsMj8hloQP8GMO9lsFfR1qjD3beMP3/GZI8TT0AtOvXDv0ooyockGMag=
  - secure: VR6rkRPxQ5NCFaxHbBwvmxUG0htnIAs+jQz/XDpnymkSimdf16fLVE5PBESspABZQcGes9uzjpNKno6U37+Tn7pcW1XtefmBNiqxMZNTFkhIDgne5QrZmtcAm+3/m2frVRi64TRrfaDH+e9Tl0+si29OVJArh1grGz3m3uwoa9VQhrqSLi989AsvcD7x16PL/PetPftih9nPSFq9Yt9mF7+M6LVfMshTzrWO8EG0dCj2wGTx60Kbf2ZRHMAryW1a9vdnHWZQcDaWZ1bsM0Qp9UM20VoYNGw01pjQv6GOBxRtgCjn4aErADrLVFcQHqylwZBUoqydsRZSUuQ9VEK04pLCVp19xP89Mmm3TMu6L+r0frC00ORlsovtCXC6eI7TbMtKz+m6FT4mM7yAXCQrmsN39o6Z17DbO+qvhhnliZy8WT/iP9FD954YTEBBp5EmYB5wEXH6amxaJwoAFUmqNSgsLf32szzRiUmKNAdvWAp59NhVE41y4mQQ/3gJGmZes7l7EurVQrt5zMlgB7CxTsi0llxwLKqVGpeHfjYsTFLnRmIPkKuebpreGFHEhhwoVKpBHT4vhe7W1gURN1rVTns8wGK+fpS7Y/KeYhKo2LcczE8eobFYf/ZAwLsNsuMC9uZrjVBS2RseuihIQMREXiTBXtspwIrk5wEGBnn3hGw=
  - secure: JoGxz+iQp8kD1eBNe1n8hoci9J954kWN7tOWBO8Fzhp0SvSiFutwWh/fM3kqpBhRGNdVqCz2Hq4698LMAhoLz2qF16SLhYr5bRvHkwUi20IwT4ekIfqgL+9/HSSEU1djEiyDDf/kTMvxcxBTGg2SWc4IlltwgCHSMZMjBvm29zowMvbunc3VlSPCKNCbzoIcuzczfAtoKLP3o4pK9EitVzqN868Sky54bHU27i2OIYbqf1GxReM5vSPcqOs4/V59YaQ3rwZJ6WnX8Pcfp6W+Bj4Nt8In26sNIYFuZbAafjMx7e5hnx9fq1hTx9mr4CcOFTOz1Qjxz7Ipd6OSiczc6G83VUL3v7zg84GlsgW7yVFokSObCtFZ9+UMqTggSyY+x0o72cdBZwzrI1EXrT8pSDFRryDzgKNe2HtGShfFeSs2Z+atPzjs1PKVY86vHLwrfepN69xi1H5Cb2XVJwgNUlmBfoTodf/akz26i4wyQHeYikBQpiPcttV/iJUd3MXjPTSzXTmOZkrIYRiskvEIwCRzlXXu5yRjgiFoPXERqCrQ/YDoJ7jKhFbukmt3MFPdMQacGmTt3XVJFvi/d1Uy12Wj+dfqJDNxUi9YB4P2MiyOBd5h7DGOMQCk992AkgSng+wM3Hf+GkeJIzaJJR6LQuvSYQrnGnqxk8gQIPFLlTM=